[AccentColor]
AccentColor=#FF0055

[Colors:Button]
BackgroundAlternate=#39260A
BackgroundNormal=#0A0A0A
DecorationFocus=#8A2BE2
DecorationHover=#FF0055
ForegroundActive=#39FF14
ForegroundInactive=#643282
ForegroundLink=#00D4FF
ForegroundNegative=#FF0055
ForegroundNeutral=#FFAA00
ForegroundNormal=#FF0055
ForegroundPositive=#39FF14
ForegroundVisited=#8A2BE2

[Colors:Complementary]
BackgroundAlternate=#140A1E
BackgroundNormal=#0A0A0A
DecorationFocus=#8A2BE2
DecorationHover=#FF0055
ForegroundActive=#39FF14
ForegroundInactive=#643282
ForegroundLink=#00D4FF
ForegroundNegative=#FF0055
ForegroundNeutral=#FFAA00
ForegroundNormal=#FF0055
ForegroundPositive=#39FF14
ForegroundVisited=#8A2BE2

[Colors:Header]
BackgroundAlternate=#140A1E
BackgroundNormal=#0A0A0A
DecorationFocus=#8A2BE2
DecorationHover=#FF0055
ForegroundActive=#39FF14
ForegroundInactive=#643282
ForegroundLink=#00D4FF
ForegroundNegative=#FF0055
ForegroundNeutral=#FFAA00
ForegroundNormal=#FF0055
ForegroundPositive=#39FF14
ForegroundVisited=#8A2BE2

[Colors:Selection]
BackgroundAlternate=#8A2BE2
BackgroundNormal=#FF0055
DecorationFocus=#39FF14
DecorationHover=#00D4FF
ForegroundActive=#FFFFFF
ForegroundInactive=#C8C8C8
ForegroundLink=#00D4FF
ForegroundNegative=#FF0055
ForegroundNeutral=#FFAA00
ForegroundNormal=#FFFFFF
ForegroundPositive=#39FF14
ForegroundVisited=#8A2BE2

[Colors:Tooltip]
BackgroundAlternate=#140A1E
BackgroundNormal=#0F0F0F
DecorationFocus=#8A2BE2
DecorationHover=#FF0055
ForegroundActive=#39FF14
ForegroundInactive=#643282
ForegroundLink=#00D4FF
ForegroundNegative=#FF0055
ForegroundNeutral=#FFAA00
ForegroundNormal=#FF0055
ForegroundPositive=#39FF14
ForegroundVisited=#8A2BE2

[Colors:View]
BackgroundAlternate=#0F0814
BackgroundNormal=#0A0A0A
DecorationFocus=#8A2BE2
DecorationHover=#FF0055
ForegroundActive=#39FF14
ForegroundInactive=#643282
ForegroundLink=#00D4FF
ForegroundNegative=#FF0055
ForegroundNeutral=#FFAA00
ForegroundNormal=#FF0055
ForegroundPositive=#39FF14
ForegroundVisited=#8A2BE2

[Colors:Window]
BackgroundAlternate=#140A1E
BackgroundNormal=#0A0A0A
DecorationFocus=#8A2BE2
DecorationHover=#FF0055
ForegroundActive=#39FF14
ForegroundInactive=#643282
ForegroundLink=#00D4FF
ForegroundNegative=#FF0055
ForegroundNeutral=#FFAA00
ForegroundNormal=#FF0055
ForegroundPositive=#39FF14
ForegroundVisited=#8A2BE2

[General]
ColorScheme=JkerNeonChaos
Name=JkerNeonChaos

[KDE]
contrast=4

[WM]
activeBackground=#0A0A0A
activeBlend=#0A0A0A
activeForeground=#FF0055
inactiveBackground=#080808
inactiveBlend=#080808
inactiveForeground=#8A2BE2
