title   Jker OS live medium (%ARCH%) with speakup screen reader
linux   /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux
initrd  /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux.img
options archisobasedir=%INSTALL_DIR% archisolabel=jker-os cow_spacesize=4G copytoram=n module_blacklist=pcspkr nouveau.modeset=1 radeon.modeset=1 nvme_load=yes accessibility=on
