[LightDM]
greeter-user=lightdm
greeter-session=lightdm-webkit2-greeter
user-session=plasma
sessions-directory=/usr/share/xsessions:/usr/share/wayland-sessions
logind-check-graphical=true

[Seat:*]
greeter-session=lightdm-webkit2-greeter
user-session=plasma
session-wrapper=/etc/lightdm/Xsession

[WebkitGreeter]
theme=jker-login
browser-debug=false
